shutdown_costmaps: false
planner_patience: 5.0
conservative_reset_dist: 3.0
planner_frequency: 0.0
oscillation_timeout: 10.0
oscillation_distance: 0.2

controller_frequency: 20.0
controller_patience: 15.0